// Performs syntax highlighting using the highlighjs library.
// Dependency on: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/go.min.js

$(document).ready(function()
{
    // If this page is also using markdown, this should be 
    // called following the markdown conversion so that any
    // codeblocks generated by it are processed.

    $('pre code').addClass('cpp');

    $('pre code').each(function(i, block)
    {
        hljs.highlightBlock(block);
    });
});
